version: '3.8'
services:
  bot:
    build: .
    env_file: .env
    restart: unless-stopped
    volumes:
      - ./models:/root/.cache/huggingface/hub  # если хотите монтировать кеш моделей
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1g
